name: stroika
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.0-227.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  auto_route: ^7.9.0
  flutter_gen: ^5.4.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  auto_route_generator: ^7.3.2
  flutter_gen_runner: ^5.4.0

  
flutter_gen:
  output: lib/shared/gen/ 
  line_length: 80 

  # Optional
  integrations:
    flutter_svg: true  


flutter:
  uses-material-design: true

  assets:
    - assets/images/png/
    - assets/images/svg/
